<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="TEAM 1: SriramSathwik Tippavaram, Hrushikesh Sai Seshagiri Chowdary Uppalapati, Jagadeshwar Kalyanapu">
<meta name="dcterms.date" content="2023-12-19">

<title>ELECTRIC VEHICLES ADOPTION ANALYSIS IN AMERICA ACROSS DIFFERENT REGIONS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="SummaryPaper_FinalProject_T1_files/libs/clipboard/clipboard.min.js"></script>
<script src="SummaryPaper_FinalProject_T1_files/libs/quarto-html/quarto.js"></script>
<script src="SummaryPaper_FinalProject_T1_files/libs/quarto-html/popper.min.js"></script>
<script src="SummaryPaper_FinalProject_T1_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="SummaryPaper_FinalProject_T1_files/libs/quarto-html/anchor.min.js"></script>
<link href="SummaryPaper_FinalProject_T1_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="SummaryPaper_FinalProject_T1_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="SummaryPaper_FinalProject_T1_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="SummaryPaper_FinalProject_T1_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="SummaryPaper_FinalProject_T1_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> ABSTRACT</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#summary-of-the-dataset" id="toc-summary-of-the-dataset" class="nav-link" data-scroll-target="#summary-of-the-dataset"><span class="header-section-number">3</span> Summary of the Dataset</a></li>
  <li><a href="#the-smart-questions" id="toc-the-smart-questions" class="nav-link" data-scroll-target="#the-smart-questions"><span class="header-section-number">4</span> The SMART Questions</a></li>
  <li><a href="#libraries" id="toc-libraries" class="nav-link" data-scroll-target="#libraries"><span class="header-section-number">5</span> LIBRARIES</a>
  <ul class="collapse">
  <li><a href="#importing-dataset" id="toc-importing-dataset" class="nav-link" data-scroll-target="#importing-dataset"><span class="header-section-number">5.1</span> Importing Dataset</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning"><span class="header-section-number">5.2</span> Data Cleaning</a></li>
  <li><a href="#data-pre-processing" id="toc-data-pre-processing" class="nav-link" data-scroll-target="#data-pre-processing"><span class="header-section-number">5.3</span> Data Pre-processing</a></li>
  </ul></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">6</span> EXPLORATORY DATA ANALYSIS</a>
  <ul class="collapse">
  <li><a href="#smart-question-1how-is-the-ev-trend-across-years-in-different-regions" id="toc-smart-question-1how-is-the-ev-trend-across-years-in-different-regions" class="nav-link" data-scroll-target="#smart-question-1how-is-the-ev-trend-across-years-in-different-regions"><span class="header-section-number">6.1</span> SMART Question 1:How is the EV trend across years in different regions?</a></li>
  <li><a href="#checking-the-ev-adoption-in-the-top5-counties-from-each-region" id="toc-checking-the-ev-adoption-in-the-top5-counties-from-each-region" class="nav-link" data-scroll-target="#checking-the-ev-adoption-in-the-top5-counties-from-each-region"><span class="header-section-number">6.2</span> Checking the EV adoption in the top5 counties from each region</a></li>
  </ul></li>
  <li><a href="#eda-of-bev-and-phevs" id="toc-eda-of-bev-and-phevs" class="nav-link" data-scroll-target="#eda-of-bev-and-phevs"><span class="header-section-number">7</span> EDA of BEV AND PHEV’s</a></li>
  <li><a href="#hypothesis-testing" id="toc-hypothesis-testing" class="nav-link" data-scroll-target="#hypothesis-testing"><span class="header-section-number">8</span> HYPOTHESIS TESTING</a>
  <ul class="collapse">
  <li><a href="#test-1" id="toc-test-1" class="nav-link" data-scroll-target="#test-1"><span class="header-section-number">8.1</span> TEST 1</a>
  <ul class="collapse">
  <li><a href="#anova-test" id="toc-anova-test" class="nav-link" data-scroll-target="#anova-test"><span class="header-section-number">8.1.1</span> ANOVA test</a></li>
  </ul></li>
  <li><a href="#test-2" id="toc-test-2" class="nav-link" data-scroll-target="#test-2"><span class="header-section-number">8.2</span> TEST 2</a>
  <ul class="collapse">
  <li><a href="#chi-square-test" id="toc-chi-square-test" class="nav-link" data-scroll-target="#chi-square-test"><span class="header-section-number">8.2.1</span> CHI-SQUARE test</a></li>
  </ul></li>
  <li><a href="#test-3" id="toc-test-3" class="nav-link" data-scroll-target="#test-3"><span class="header-section-number">8.3</span> TEST 3</a>
  <ul class="collapse">
  <li><a href="#t-test" id="toc-t-test" class="nav-link" data-scroll-target="#t-test"><span class="header-section-number">8.3.1</span> T-Test</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#modelling" id="toc-modelling" class="nav-link" data-scroll-target="#modelling"><span class="header-section-number">9</span> MODELLING</a>
  <ul class="collapse">
  <li><a href="#ols-regression" id="toc-ols-regression" class="nav-link" data-scroll-target="#ols-regression"><span class="header-section-number">9.1</span> OLS Regression</a>
  <ul class="collapse">
  <li><a href="#smart-question-4-is-there-a-relationship-between-the-year-and-total-vehicle-count-in-predicting-regional-ev-adoption" id="toc-smart-question-4-is-there-a-relationship-between-the-year-and-total-vehicle-count-in-predicting-regional-ev-adoption" class="nav-link" data-scroll-target="#smart-question-4-is-there-a-relationship-between-the-year-and-total-vehicle-count-in-predicting-regional-ev-adoption"><span class="header-section-number">9.1.1</span> SMART QUESTION 4: Is there a relationship between the year and total vehicle count in predicting regional EV adoption?</a></li>
  </ul></li>
  <li><a href="#logisticregression" id="toc-logisticregression" class="nav-link" data-scroll-target="#logisticregression"><span class="header-section-number">9.2</span> LogisticRegression</a>
  <ul class="collapse">
  <li><a href="#smart-q5-can-demographic-and-regional-factors-such-as-year-state-and-region-effectively-predict-the-likelihood-of-a-county-having-high-electric-vehicle-adoption-rates" id="toc-smart-q5-can-demographic-and-regional-factors-such-as-year-state-and-region-effectively-predict-the-likelihood-of-a-county-having-high-electric-vehicle-adoption-rates" class="nav-link" data-scroll-target="#smart-q5-can-demographic-and-regional-factors-such-as-year-state-and-region-effectively-predict-the-likelihood-of-a-county-having-high-electric-vehicle-adoption-rates"><span class="header-section-number">9.2.1</span> SMART Q5: Can demographic and regional factors, such as year, state, and region, effectively predict the likelihood of a county having high electric vehicle adoption rates?</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#future-scope" id="toc-future-scope" class="nav-link" data-scroll-target="#future-scope"><span class="header-section-number">10</span> FUTURE SCOPE</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">11</span> CONCLUSION</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">12</span> REFERENCES</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ELECTRIC VEHICLES ADOPTION ANALYSIS IN AMERICA ACROSS DIFFERENT REGIONS</h1>
<p class="subtitle lead">DATS 6103: An Introduction to Data Mining</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>TEAM 1: SriramSathwik Tippavaram, Hrushikesh Sai Seshagiri Chowdary Uppalapati, Jagadeshwar Kalyanapu </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 19, 2023</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> ABSTRACT</h1>
<p>This study delves into the dynamics of electric vehicle (EV) adoption across different regions in the United States, highlighting regional disparities and EV growth trends. The study investigates factors influencing adoption rates, such as state policies, economic incentives, and infrastructure development, using a large dataset. The goal is to identify patterns and potential areas for policy intervention by better understanding the impact of regional characteristics on EV popularity. This analysis is critical for automotive industry stakeholders, policymakers, and environmental advocates, as it provides insight into the future trajectory of sustainable transportation in America.</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>The transition to electric vehicles (EVs) is a critical component of the global transition to sustainability, particularly in the context of the United States, where transportation contributes significantly to carbon emissions. The purpose of this study is to dissect the complexities of EV adoption across various American regions, highlighting the disparities and underlying factors that influence this trend. The study’s foundation is a large dataset that reflects the multifaceted nature of EV proliferation, including variables like vehicle types, regional distributions, and chronological adoption trends.</p>
<p>The dataset’s richness allows for in-depth exploration of state-by-state vehicle counts, county-level data, and vehicle primary use categories. This study not only highlights the current state of EV adoption, but also delves into the economic, policy-driven, and infrastructure factors driving this movement. This type of analysis is critical for policymakers, industry stakeholders, and environmentalists because it provides actionable insights to encourage EV integration.</p>
<p>In essence, this study not only maps the current landscape of EV adoption in the United States, but it also serves as a strategic guide for navigating the challenges and capitalising on the opportunities in this domain. It exemplifies the potential of sustainable transport and the critical role of informed decision-making in meeting environmental targets.</p>
</section>
<section id="summary-of-the-dataset" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Summary of the Dataset</h1>
<p>This study’s dataset includes extensive records of electric vehicle (EV) adoption across the United States. It contains information such as vehicle counts, types (BEVs and PHEVs), regional distribution, and year-to-year trends. The dataset also includes demographic and geographic information, allowing for a thorough examination of regional disparities in EV adoption. Critical features like state-by-state vehicle totals, county-level data, and primary use categories provide a comprehensive picture of the EV landscape. This rich dataset serves as the foundation for our analysis, allowing for a more nuanced understanding of the factors driving EV adoption across America.</p>
</section>
<section id="the-smart-questions" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> The SMART Questions</h1>
<p>This study is organised around five critical SMART questions in order to gain a comprehensive understanding of the dynamics surrounding electric vehicle adoption in the United States. These questions have been carefully crafted to be specific, measurable, achievable, relevant, and time-bound in order to provide targeted insights and tangible results.</p>
<ol type="1">
<li><p>How is the EV trend across years in different regions?</p></li>
<li><p>Is there a statistically significant association between geographic regions and the primary use categories of electric vehicles?</p></li>
<li><p>Can demographic and regional factors, such as year, state, and region, effectively predict the likelihood of a county having high electric vehicle adoption rates?</p></li>
<li><p>Is there a significant difference in the average number of electric vehicles (EVs) between the top 5 counties of the South region and the top 5 counties of the Northeast region in the United States?</p></li>
<li><p>Is there a relationship between the year and total vehicle count in predicting regional EV adoption?</p></li>
</ol>
</section>
<section id="libraries" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> LIBRARIES</h1>
<div class="cell" data-execution_count="1">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span>  scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> f_oneway</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2_contingency</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.patches <span class="im">as</span> mpatches</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="importing-dataset" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="importing-dataset"><span class="header-section-number">5.1</span> Importing Dataset</h2>
<div class="cell" data-execution_count="2">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>file_path <span class="op">=</span> <span class="st">'EV_POPULATION_DATASET.csv'</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>ev_data <span class="op">=</span> pd.read_csv(file_path)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ev_data.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Date    County State Vehicle Primary Use  \
0      June 30 2017  Okaloosa    FL           Passenger   
1  December 31 2021  Stafford    VA           Passenger   
2     March 31 2022    Camden    NJ           Passenger   
3   October 31 2019  Franklin    MA           Passenger   
4  November 30 2021  Harrison    MS           Passenger   

   Battery Electric Vehicles (BEVs)  Plug-In Hybrid Electric Vehicles (PHEVs)  \
0                                 1                                         0   
1                                 2                                         1   
2                                 0                                         1   
3                                 0                                         1   
4                                 2                                         0   

   Electric Vehicle (EV) Total  Non-Electric Vehicle Total  Total Vehicles  \
0                            1                         185             186   
1                            3                          94              97   
2                            1                          13              14   
3                            1                           1               2   
4                            2                          46              48   

   Percent Electric Vehicles  
0                       0.54  
1                       3.09  
2                       7.14  
3                      50.00  
4                       4.17  </code></pre>
</div>
</div>
</section>
<section id="data-cleaning" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="data-cleaning"><span class="header-section-number">5.2</span> Data Cleaning</h2>
<div class="cell" data-execution_count="3">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Checking for null values in the dataset</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>null_values <span class="op">=</span> ev_data.isnull().<span class="bu">sum</span>()</span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(null_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Date                                         0
County                                      81
State                                       81
Vehicle Primary Use                          0
Battery Electric Vehicles (BEVs)             0
Plug-In Hybrid Electric Vehicles (PHEVs)     0
Electric Vehicle (EV) Total                  0
Non-Electric Vehicle Total                   0
Total Vehicles                               0
Percent Electric Vehicles                    0
dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="4">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>ev_data_cleaned <span class="op">=</span> ev_data.dropna()</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Displaying the first few rows of the cleaned DataFrame</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">len</span>(ev_data_cleaned))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>12688</code></pre>
</div>
</div>
<p><strong>Observation:</strong> The “County” and “State” columns each have 81 missing values. There are no missing values in the remaining columns, which include various metrics related to electric vehicles. Addressing missing values in “County” and “State” may be required for a thorough analysis.</p>
</section>
<section id="data-pre-processing" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="data-pre-processing"><span class="header-section-number">5.3</span> Data Pre-processing</h2>
<div class="cell" data-execution_count="5">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co">#divide sates based on region</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>state_region_map <span class="op">=</span> {</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'WA'</span>: <span class="st">'West'</span>, <span class="st">'OR'</span>: <span class="st">'West'</span>, <span class="st">'CA'</span>: <span class="st">'West'</span>, <span class="st">'AK'</span>: <span class="st">'West'</span>, <span class="st">'HI'</span>: <span class="st">'West'</span>, <span class="st">'NV'</span>: <span class="st">'West'</span>, <span class="st">'ID'</span>: <span class="st">'West'</span>,</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'MT'</span>: <span class="st">'West'</span>, <span class="st">'WY'</span>: <span class="st">'West'</span>, <span class="st">'UT'</span>: <span class="st">'West'</span>, <span class="st">'AZ'</span>: <span class="st">'West'</span>, <span class="st">'CO'</span>: <span class="st">'West'</span>, <span class="st">'NM'</span>: <span class="st">'West'</span>,</span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'ND'</span>: <span class="st">'Midwest'</span>, <span class="st">'SD'</span>: <span class="st">'Midwest'</span>, <span class="st">'NE'</span>: <span class="st">'Midwest'</span>, <span class="st">'KS'</span>: <span class="st">'Midwest'</span>, <span class="st">'MN'</span>: <span class="st">'Midwest'</span>, <span class="st">'IA'</span>: <span class="st">'Midwest'</span>, <span class="st">'MO'</span>: <span class="st">'Midwest'</span>,</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>    <span class="st">'WI'</span>: <span class="st">'Midwest'</span>, <span class="st">'IL'</span>: <span class="st">'Midwest'</span>, <span class="st">'MI'</span>: <span class="st">'Midwest'</span>, <span class="st">'IN'</span>: <span class="st">'Midwest'</span>, <span class="st">'OH'</span>: <span class="st">'Midwest'</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    <span class="st">'PA'</span>: <span class="st">'Northeast'</span>, <span class="st">'NY'</span>: <span class="st">'Northeast'</span>, <span class="st">'VT'</span>: <span class="st">'Northeast'</span>, <span class="st">'NH'</span>: <span class="st">'Northeast'</span>, <span class="st">'ME'</span>: <span class="st">'Northeast'</span>, <span class="st">'MA'</span>: <span class="st">'Northeast'</span>,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="st">'RI'</span>: <span class="st">'Northeast'</span>, <span class="st">'CT'</span>: <span class="st">'Northeast'</span>, <span class="st">'NJ'</span>: <span class="st">'Northeast'</span>, <span class="st">'DE'</span>: <span class="st">'Northeast'</span>, <span class="st">'MD'</span>: <span class="st">'Northeast'</span>,</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="st">'WV'</span>: <span class="st">'South'</span>, <span class="st">'VA'</span>: <span class="st">'South'</span>, <span class="st">'KY'</span>: <span class="st">'South'</span>, <span class="st">'TN'</span>: <span class="st">'South'</span>, <span class="st">'NC'</span>: <span class="st">'South'</span>, <span class="st">'SC'</span>: <span class="st">'South'</span>, <span class="st">'GA'</span>: <span class="st">'South'</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="st">'FL'</span>: <span class="st">'South'</span>, <span class="st">'AL'</span>: <span class="st">'South'</span>, <span class="st">'MS'</span>: <span class="st">'South'</span>, <span class="st">'AR'</span>: <span class="st">'South'</span>, <span class="st">'LA'</span>: <span class="st">'South'</span>, <span class="st">'TX'</span>: <span class="st">'South'</span>, <span class="st">'OK'</span>: <span class="st">'South'</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>ev_data_cleaned[<span class="st">'Region'</span>] <span class="op">=</span> ev_data_cleaned[<span class="st">'State'</span>].<span class="bu">map</span>(state_region_map)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ev_data_cleaned.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>               Date    County State Vehicle Primary Use  \
0      June 30 2017  Okaloosa    FL           Passenger   
1  December 31 2021  Stafford    VA           Passenger   
2     March 31 2022    Camden    NJ           Passenger   
3   October 31 2019  Franklin    MA           Passenger   
4  November 30 2021  Harrison    MS           Passenger   

   Battery Electric Vehicles (BEVs)  Plug-In Hybrid Electric Vehicles (PHEVs)  \
0                                 1                                         0   
1                                 2                                         1   
2                                 0                                         1   
3                                 0                                         1   
4                                 2                                         0   

   Electric Vehicle (EV) Total  Non-Electric Vehicle Total  Total Vehicles  \
0                            1                         185             186   
1                            3                          94              97   
2                            1                          13              14   
3                            1                           1               2   
4                            2                          46              48   

   Percent Electric Vehicles     Region  
0                       0.54      South  
1                       3.09      South  
2                       7.14  Northeast  
3                      50.00  Northeast  
4                       4.17      South  </code></pre>
</div>
</div>
<div class="cell" data-execution_count="6">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>ev_data_cleaned.rename(columns<span class="op">=</span>{<span class="st">'Date'</span>: <span class="st">'Year'</span>}, inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell" data-execution_count="7">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co">#Converting Date column</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Preprocess the 'Date' column by converting it to datetime format</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>ev_data_cleaned[<span class="st">'Year'</span>] <span class="op">=</span> pd.to_datetime(ev_data_cleaned[<span class="st">'Year'</span>], errors<span class="op">=</span><span class="st">'coerce'</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Replace the 'Date' column with just the year component</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ev_data_cleaned[<span class="st">'Year'</span>] <span class="op">=</span> ev_data_cleaned[<span class="st">'Year'</span>].dt.year.astype(<span class="st">'Int64'</span>)  <span class="co"># Using 'Int64' to handle NaT (missing dates) properly</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ev_data_cleaned.head())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Year    County State Vehicle Primary Use  Battery Electric Vehicles (BEVs)  \
0  2017  Okaloosa    FL           Passenger                                 1   
1  2021  Stafford    VA           Passenger                                 2   
2  2022    Camden    NJ           Passenger                                 0   
3  2019  Franklin    MA           Passenger                                 0   
4  2021  Harrison    MS           Passenger                                 2   

   Plug-In Hybrid Electric Vehicles (PHEVs)  Electric Vehicle (EV) Total  \
0                                         0                            1   
1                                         1                            3   
2                                         1                            1   
3                                         1                            1   
4                                         0                            2   

   Non-Electric Vehicle Total  Total Vehicles  Percent Electric Vehicles  \
0                         185             186                       0.54   
1                          94              97                       3.09   
2                          13              14                       7.14   
3                           1               2                      50.00   
4                          46              48                       4.17   

      Region  
0      South  
1      South  
2  Northeast  
3  Northeast  
4      South  </code></pre>
</div>
</div>
<p><strong>Observation:</strong> Based on the all the pre-processing steps above, several critical steps are taken in the provided data pre-processing code to prepare the dataset for analysis. To begin, the dataset is divided into regions based on the states, and for this we have used dictionaries to map unique states based on the regions. The ‘Date’ column is then renamed ‘Year’ for clarity. Finally, the ‘Year’ column is converted to a datetime format and refined further to extract the year component, resulting in consistent and accurate date data for analysis. These steps improve data clarity and allow for more meaningful insights into electric vehicle trends over time.</p>
<div class="cell" data-execution_count="8">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>output_file_path <span class="op">=</span> <span class="st">'dataset_new.csv'</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>ev_data_cleaned.to_csv(output_file_path, index<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>df<span class="op">=</span>pd.read_csv(<span class="st">'dataset_new.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p><strong>Observation:</strong> Many columns are in object type datatypes, but we want to convert them to categorical variables.</p>
<p>Object to categorical variable conversion</p>
</section>
</section>
<section id="exploratory-data-analysis" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> EXPLORATORY DATA ANALYSIS</h1>
<div class="cell" data-execution_count="9">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Setting the aesthetics for the plots</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>sns.<span class="bu">set</span>(style<span class="op">=</span><span class="st">"whitegrid"</span>)</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization 1: Trend of Electric Vehicle Adoption Over Time</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>df.groupby(<span class="st">'Year'</span>)[<span class="st">'Electric Vehicle (EV) Total'</span>].<span class="bu">sum</span>().plot(kind<span class="op">=</span><span class="st">'line'</span>, marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Trend of Electric Vehicle Adoption Over Time'</span>)</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Number of Electric Vehicles'</span>)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization 2: Regional Distribution of Electric Vehicles</span></span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>sns.barplot(x<span class="op">=</span><span class="st">'Region'</span>, y<span class="op">=</span><span class="st">'Electric Vehicle (EV) Total'</span>, data<span class="op">=</span>df, estimator<span class="op">=</span><span class="bu">sum</span>, ci<span class="op">=</span><span class="va">None</span>)</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Regional Distribution of Electric Vehicles'</span>)</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Region'</span>)</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Number of Electric Vehicles'</span>)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-10-output-1.png" width="1136" height="560"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-10-output-2.png" width="944" height="560"></p>
</div>
</div>
<p><strong>Observation:</strong> <strong>Trend of Electric Vehicle Adoption Over Time:</strong> From 2017 to 2021, the line chart shows a consistent upward trajectory in electric vehicle adoption, indicating robust growth. The drop in 2023 suggests a possible market contraction or reporting anomaly that should be investigated further.</p>
<p><strong>Regional Distribution of Electric Vehicles:</strong> This bar chart shows a significant regional variation in EV adoption, with the West far ahead. It emphasises the uneven adoption of electric vehicles, pointing to regional preferences or disparities in infrastructure and policy support.</p>
<section id="smart-question-1how-is-the-ev-trend-across-years-in-different-regions" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="smart-question-1how-is-the-ev-trend-across-years-in-different-regions"><span class="header-section-number">6.1</span> SMART Question 1:How is the EV trend across years in different regions?</h2>
<div class="cell" data-execution_count="10">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualization: Trend of Electric Vehicles Over the Years by Region</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">14</span>, <span class="dv">7</span>))</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>sns.lineplot(data<span class="op">=</span>df, x<span class="op">=</span><span class="st">'Year'</span>, y<span class="op">=</span><span class="st">'Electric Vehicle (EV) Total'</span>, hue<span class="op">=</span><span class="st">'Region'</span>, marker<span class="op">=</span><span class="st">'o'</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Trend of Electric Vehicles Over the Years by Region'</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Year'</span>)</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Total Electric Vehicles'</span>)</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">'Region'</span>, loc<span class="op">=</span><span class="st">'upper left'</span>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>plt.grid(<span class="va">True</span>)</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-11-output-1.png" width="1114" height="603"></p>
</div>
</div>
<p><strong>Conclusion for the SMART Q1:</strong> The multi-line chart with confidence intervals demonstrates that, while all regions are experiencing growth in EV adoption, the West region’s pace is noticeably faster. The graph also suggests that regional disparities in EV adoption rates are increasing over time.</p>
</section>
<section id="checking-the-ev-adoption-in-the-top5-counties-from-each-region" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="checking-the-ev-adoption-in-the-top5-counties-from-each-region"><span class="header-section-number">6.2</span> Checking the EV adoption in the top5 counties from each region</h2>
<div class="cell" data-execution_count="11">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_top_5_counties_for_region(dataframe, region_name):</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Filter for the current region</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    region_df <span class="op">=</span> dataframe[dataframe[<span class="st">'Region'</span>] <span class="op">==</span> region_name]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Group by 'County' and sum up the EV totals</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    ev_totals <span class="op">=</span> region_df.groupby(<span class="st">'County'</span>)[<span class="st">'Electric Vehicle (EV) Total'</span>].<span class="bu">sum</span>()</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sort and get the top 5 counties</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>    top_5_counties <span class="op">=</span> ev_totals.nlargest(<span class="dv">5</span>)</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Create the bar chart</span></span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    sns.barplot(x<span class="op">=</span>top_5_counties.index, y<span class="op">=</span>top_5_counties.values, palette<span class="op">=</span><span class="st">'viridis'</span>)</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'Top 5 Counties in EV Adoption in </span><span class="sc">{</span>region_name<span class="sc">}</span><span class="ss"> Region'</span>)</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">'County'</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">'Total EVs'</span>)</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot for a single region as an example</span></span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>plot_top_5_counties_for_region(df, <span class="st">'South'</span>)</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-12-output-1.png" width="969" height="592"></p>
</div>
</div>
<p><strong>Observation:</strong> The bar chart indicates Fairfax County leads in EV adoption within the South region, followed by Bexar and others. This may reflect differing economic dynamics, policy incentives, or consumer behaviors at the county level within the region.</p>
<div class="cell" data-execution_count="12">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>plot_top_5_counties_for_region(df, <span class="st">'Midwest'</span>)</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-13-output-1.png" width="969" height="569"></p>
</div>
</div>
<p><strong>Observation:</strong> The top counties in the Midwest region have a more even distribution of EV adoption. Hennepin and Page counties lead, with Douglas close behind, indicating a more homogeneous adoption pattern among the top performers in this region.</p>
<div class="cell" data-execution_count="13">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">12</span>, <span class="dv">6</span>))</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>plot_top_5_counties_for_region(df, <span class="st">'West'</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-14-output-1.png" width="977" height="581"></p>
</div>
</div>
<p><strong>Observation:</strong> San Diego leads the West in EV adoption, with significant contributions from Los Angeles and Santa Clara. The chart indicates that California’s urban counties have a high concentration of EVs, most likely due to favourable policies and infrastructure.</p>
</section>
</section>
<section id="eda-of-bev-and-phevs" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> EDA of BEV AND PHEV’s</h1>
<div class="cell" data-execution_count="14">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Grouping the data by state and summing up the BEVs and PHEVs</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>state_ev_totals <span class="op">=</span> df.groupby(<span class="st">'State'</span>)[[<span class="st">'Battery Electric Vehicles (BEVs)'</span>, <span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>]].<span class="bu">sum</span>()</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Sorting the states based on the total number of EVs (BEVs + PHEVs)</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>state_ev_totals[<span class="st">'Total EVs'</span>] <span class="op">=</span> state_ev_totals[<span class="st">'Battery Electric Vehicles (BEVs)'</span>] <span class="op">+</span> state_ev_totals[<span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>]</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>state_ev_totals_sorted <span class="op">=</span> state_ev_totals.sort_values(by<span class="op">=</span><span class="st">'Total EVs'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting a stacked bar chart</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>state_ev_totals_sorted[[<span class="st">'Battery Electric Vehicles (BEVs)'</span>, <span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>]].plot(kind<span class="op">=</span><span class="st">'bar'</span>, stacked<span class="op">=</span><span class="va">True</span>, figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">8</span>))</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Adoption of BEVs and PHEVs by State'</span>)</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'State'</span>)</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Electric Vehicles'</span>)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>plt.legend(title<span class="op">=</span><span class="st">'Vehicle Type'</span>)</span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the plot</span></span>
<span id="cb19-19"><a href="#cb19-19" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-15-output-1.png" width="1424" height="752"></p>
</div>
</div>
<p><strong>Observation:</strong> When compared to other states, California has a significant lead in the adoption of both BEVs and PHEVs, reflecting its pioneering role in EV adoption. This stacked bar chart highlights the state’s dominance in the EV market.</p>
<div class="cell" data-execution_count="15">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Bar Chart of Average EVs by State</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>average_evs_by_state <span class="op">=</span> df.groupby(<span class="st">'State'</span>)[<span class="st">'Electric Vehicle (EV) Total'</span>].mean().sort_values(ascending<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">8</span>))</span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>average_evs_by_state.plot(kind<span class="op">=</span><span class="st">'bar'</span>, color<span class="op">=</span><span class="st">'skyblue'</span>)</span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Average Number of EVs by State'</span>)</span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'State'</span>)</span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Average Number of EVs'</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-16-output-1.png" width="1178" height="689"></p>
</div>
</div>
<p><strong>Observation:</strong> Arizona leads the way in average EVs per state, indicating high adoption rates, which could be attributed to favourable incentives or infrastructure. The descending order contrasts sharply with states at the opposite end of the spectrum, where adoption is clearly lower.</p>
<div class="cell" data-execution_count="16">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>bevs_by_region <span class="op">=</span> df.groupby(<span class="st">'Region'</span>)[<span class="st">'Battery Electric Vehicles (BEVs)'</span>].<span class="bu">sum</span>()</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>phevs_by_region <span class="op">=</span> df.groupby(<span class="st">'Region'</span>)[<span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>].<span class="bu">sum</span>()</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Stacking BEVs and PHEVs</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">6</span>))</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>plt.bar(bevs_by_region.index, bevs_by_region, label<span class="op">=</span><span class="st">'BEVs'</span>, color<span class="op">=</span><span class="st">'blue'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>plt.bar(phevs_by_region.index, phevs_by_region, bottom<span class="op">=</span>bevs_by_region, label<span class="op">=</span><span class="st">'PHEVs'</span>, color<span class="op">=</span><span class="st">'orange'</span>, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Comparison of BEVs and PHEVs by Region'</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Region'</span>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Vehicles'</span>)</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>plt.legend()</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-17-output-1.png" width="837" height="529"></p>
</div>
</div>
<p><strong>Observation:</strong> The West leads not only in total EV numbers, but also in the preference for BEVs over PHEVs. The chart highlights regional differences in vehicle type preferences, with the West favouring all-electric vehicles.</p>
<div class="cell" data-execution_count="17">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Assuming df1 is already loaded and preprocessed as before</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>county_region_grouped <span class="op">=</span> df.groupby([<span class="st">'Region'</span>, <span class="st">'County'</span>]).agg({</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Battery Electric Vehicles (BEVs)'</span>: <span class="st">'sum'</span>, </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>: <span class="st">'sum'</span></span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>}).reset_index()</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a total EVs column for sorting</span></span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>county_region_grouped[<span class="st">'Total EVs'</span>] <span class="op">=</span> county_region_grouped[<span class="st">'Battery Electric Vehicles (BEVs)'</span>] <span class="op">+</span> county_region_grouped[<span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>]</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Sorting to get the top 20 counties overall based on total EVs</span></span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>top_20_counties_overall <span class="op">=</span> county_region_grouped.sort_values(by<span class="op">=</span><span class="st">'Total EVs'</span>, ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">20</span>)</span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting the unique regions from the top 20 counties</span></span>
<span id="cb22-17"><a href="#cb22-17" aria-hidden="true" tabindex="-1"></a>regions <span class="op">=</span> top_20_counties_overall[<span class="st">'Region'</span>].unique()</span>
<span id="cb22-18"><a href="#cb22-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-19"><a href="#cb22-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Assigning different colors for each region using NumPy</span></span>
<span id="cb22-20"><a href="#cb22-20" aria-hidden="true" tabindex="-1"></a>colors <span class="op">=</span> plt.cm.viridis(np.linspace(<span class="dv">0</span>, <span class="dv">1</span>, <span class="bu">len</span>(regions)))</span>
<span id="cb22-21"><a href="#cb22-21" aria-hidden="true" tabindex="-1"></a>region_colors <span class="op">=</span> {region: color <span class="cf">for</span> region, color <span class="kw">in</span> <span class="bu">zip</span>(regions, colors)}</span>
<span id="cb22-22"><a href="#cb22-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-23"><a href="#cb22-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating the bar plot for the top 20 counties, colored by their region</span></span>
<span id="cb22-24"><a href="#cb22-24" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>, <span class="dv">8</span>))</span>
<span id="cb22-25"><a href="#cb22-25" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> _, row <span class="kw">in</span> top_20_counties_overall.iterrows():</span>
<span id="cb22-26"><a href="#cb22-26" aria-hidden="true" tabindex="-1"></a>    plt.bar(row[<span class="st">'County'</span>], row[<span class="st">'Battery Electric Vehicles (BEVs)'</span>], color<span class="op">=</span>region_colors[row[<span class="st">'Region'</span>]], edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb22-27"><a href="#cb22-27" aria-hidden="true" tabindex="-1"></a>    plt.bar(row[<span class="st">'County'</span>], row[<span class="st">'Plug-In Hybrid Electric Vehicles (PHEVs)'</span>], bottom<span class="op">=</span>row[<span class="st">'Battery Electric Vehicles (BEVs)'</span>], color<span class="op">=</span>region_colors[row[<span class="st">'Region'</span>]], alpha<span class="op">=</span><span class="fl">0.5</span>, edgecolor<span class="op">=</span><span class="st">'white'</span>)</span>
<span id="cb22-28"><a href="#cb22-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-29"><a href="#cb22-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Creating a custom legend</span></span>
<span id="cb22-30"><a href="#cb22-30" aria-hidden="true" tabindex="-1"></a>legend_patches <span class="op">=</span> [mpatches.Patch(color<span class="op">=</span>color, label<span class="op">=</span>region) <span class="cf">for</span> region, color <span class="kw">in</span> region_colors.items()]</span>
<span id="cb22-31"><a href="#cb22-31" aria-hidden="true" tabindex="-1"></a>plt.legend(handles<span class="op">=</span>legend_patches, title<span class="op">=</span><span class="st">'Region'</span>)</span>
<span id="cb22-32"><a href="#cb22-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-33"><a href="#cb22-33" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Top 20 Counties in EV Adoption (BEVs and PHEVs) by Region'</span>)</span>
<span id="cb22-34"><a href="#cb22-34" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'County'</span>)</span>
<span id="cb22-35"><a href="#cb22-35" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Number of Vehicles'</span>)</span>
<span id="cb22-36"><a href="#cb22-36" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb22-37"><a href="#cb22-37" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="SummaryPaper_FinalProject_T1_files/figure-html/cell-18-output-1.png" width="1200" height="738"></p>
</div>
</div>
<p><strong>Observation:</strong> In terms of total EV adoption, San Diego and Los Angeles counties have a significant lead. The graphic depicts regional EV hotspots, with the West, particularly California, dominating the chart, reflecting regional policy success and consumer preference for electric mobility.</p>
</section>
<section id="hypothesis-testing" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> HYPOTHESIS TESTING</h1>
<section id="test-1" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="test-1"><span class="header-section-number">8.1</span> TEST 1</h2>
<section id="anova-test" class="level3" data-number="8.1.1">
<h3 data-number="8.1.1" class="anchored" data-anchor-id="anova-test"><span class="header-section-number">8.1.1</span> ANOVA test</h3>
<section id="is-there-a-significant-difference-in-the-average-number-of-evs-among-different-years-comparing-2017-2019-and-2021" class="level4" data-number="8.1.1.1">
<h4 data-number="8.1.1.1" class="anchored" data-anchor-id="is-there-a-significant-difference-in-the-average-number-of-evs-among-different-years-comparing-2017-2019-and-2021"><span class="header-section-number">8.1.1.1</span> Is there a significant difference in the average number of EVs among different years (comparing 2017, 2019, and 2021)?</h4>
<div class="cell" data-execution_count="18">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Null Hypothesis (H0): There is no significant difference in the average number of EVs among the years 2017, 2019, and 2021. </span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co">#This implies that any observed differences are due to random chance.</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Alternative Hypothesis (H1): There is a significant difference in the average number of EVs among these years, indicating that changes over the years are not just random variations.</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> f_oneway</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>df_years <span class="op">=</span> df[df[<span class="st">'Year'</span>].isin([<span class="dv">2017</span>, <span class="dv">2019</span>, <span class="dv">2021</span>])]</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the EV totals for each of these years</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>data_2017 <span class="op">=</span> df_years[df_years[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2017</span>][<span class="st">'Electric Vehicle (EV) Total'</span>]</span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>data_2019 <span class="op">=</span> df_years[df_years[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2019</span>][<span class="st">'Electric Vehicle (EV) Total'</span>]</span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a>data_2021 <span class="op">=</span> df_years[df_years[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2021</span>][<span class="st">'Electric Vehicle (EV) Total'</span>]</span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform ANOVA test</span></span>
<span id="cb23-19"><a href="#cb23-19" aria-hidden="true" tabindex="-1"></a>anova_result <span class="op">=</span> f_oneway(data_2017, data_2019, data_2021)</span>
<span id="cb23-20"><a href="#cb23-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-21"><a href="#cb23-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the result</span></span>
<span id="cb23-22"><a href="#cb23-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(anova_result)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>F_onewayResult(statistic=25.423195756856018, pvalue=1.0250901376196195e-11)</code></pre>
</div>
</div>
<p><strong>Observation:</strong> The ANOVA test reveals a highly significant difference in the average number of EVs between 2017, 2019, and 2021 (p-value 0.00001). The statistic shows a statistically significant change in EV numbers over these years, implying that the factors influencing EV adoption have evolved, resulting in fluctuations in annual EV adoption rates. This finding calls for more research into the specific annual factors influencing these variations, such as policy changes, technological advancements, or economic incentives.</p>
</section>
</section>
</section>
<section id="test-2" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="test-2"><span class="header-section-number">8.2</span> TEST 2</h2>
<section id="chi-square-test" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="chi-square-test"><span class="header-section-number">8.2.1</span> CHI-SQUARE test</h3>
<section id="smart-question-2-is-there-a-statistically-significant-association-between-geographic-regions-and-the-primary-use-categories-of-electric-vehicles" class="level4" data-number="8.2.1.1">
<h4 data-number="8.2.1.1" class="anchored" data-anchor-id="smart-question-2-is-there-a-statistically-significant-association-between-geographic-regions-and-the-primary-use-categories-of-electric-vehicles"><span class="header-section-number">8.2.1.1</span> SMART QUESTION 2: Is there a statistically significant association between geographic regions and the primary use categories of electric vehicles?</h4>
<div class="cell" data-execution_count="19">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> chi2_contingency</span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a><span class="co">#Null Hypothesis (H0): There is no association between the region and the vehicle primary use category in terms of EV adoption.</span></span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a><span class="co">#This means any observed association is due to random chance.</span></span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a><span class="co">#Alternative Hypothesis (H1): There is an association between the region and the vehicle primary use  category in terms of EV adoption. </span></span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a><span class="co">#This means the observed association is not due to random chance.</span></span>
<span id="cb25-10"><a href="#cb25-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-11"><a href="#cb25-11" aria-hidden="true" tabindex="-1"></a>contingency_table <span class="op">=</span> pd.crosstab(df[<span class="st">'Region'</span>], df[<span class="st">'Vehicle Primary Use'</span>])</span>
<span id="cb25-12"><a href="#cb25-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-13"><a href="#cb25-13" aria-hidden="true" tabindex="-1"></a>chi2, p_value, dof, expected <span class="op">=</span> chi2_contingency(contingency_table)</span>
<span id="cb25-14"><a href="#cb25-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-15"><a href="#cb25-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Output the results</span></span>
<span id="cb25-16"><a href="#cb25-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Chi-square statistic:"</span>, chi2)</span>
<span id="cb25-17"><a href="#cb25-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"p-value:"</span>, p_value)</span>
<span id="cb25-18"><a href="#cb25-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"</span><span class="ch">\n</span><span class="st">Contingency Table:"</span>)</span>
<span id="cb25-19"><a href="#cb25-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(contingency_table)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Chi-square statistic: 19.06683791983831
p-value: 0.00026483531434350613

Contingency Table:
Vehicle Primary Use  Passenger  Truck
Region                               
Midwest                   1575     12
Northeast                 2302      0
South                     4921     12
West                      3724     15</code></pre>
</div>
</div>
<p><strong>Conclusion for SMART Q2:</strong></p>
<p>The chi-square test reveals a significant relationship between geographic regions and electric vehicle primary use categories (p-value 0.001). The contingency table reveals regional disparities, with the South leading in passenger EVs and the West balancing passenger and truck categories. This suggests regional differences in EV usage patterns, which could be influenced by regional lifestyles, infrastructure, or economic factors.</p>
</section>
</section>
</section>
<section id="test-3" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="test-3"><span class="header-section-number">8.3</span> TEST 3</h2>
<section id="t-test" class="level3" data-number="8.3.1">
<h3 data-number="8.3.1" class="anchored" data-anchor-id="t-test"><span class="header-section-number">8.3.1</span> T-Test</h3>
<section id="smart-question3-is-there-a-significant-difference-in-the-average-number-of-electric-vehicles-evs-between-the-top-5-counties-of-the-south-region-and-the-top-5-counties-of-the-northeast-region-in-the-united-states" class="level4" data-number="8.3.1.1">
<h4 data-number="8.3.1.1" class="anchored" data-anchor-id="smart-question3-is-there-a-significant-difference-in-the-average-number-of-electric-vehicles-evs-between-the-top-5-counties-of-the-south-region-and-the-top-5-counties-of-the-northeast-region-in-the-united-states"><span class="header-section-number">8.3.1.1</span> SMART QUESTION3: Is there a significant difference in the average number of electric vehicles (EVs) between the top 5 counties of the South region and the top 5 counties of the Northeast region in the United States?</h4>
<div class="cell" data-execution_count="20">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> ttest_ind</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="co">#H0 The mean number of EVs in the top 5 counties of the South region is equal to or greater than the mean number of EVs in the top 5 counties of the Northeast region. </span></span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="co">#H1: The mean number of EVs in the top 5 counties of the South region is less than the mean number of EVs in the top 5 counties of the Northeast region.</span></span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>data_2023_northeast <span class="op">=</span> df[(df[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2023</span>) <span class="op">&amp;</span> (df[<span class="st">'Region'</span>] <span class="op">==</span> <span class="st">'Northeast'</span>)]</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>county_ev_totals_northeast <span class="op">=</span> data_2023_northeast.groupby(<span class="st">'County'</span>)[<span class="st">'Electric Vehicle (EV) Total'</span>].<span class="bu">sum</span>()</span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>top5_counties_northeast <span class="op">=</span> county_ev_totals_northeast.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>)</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>data_2023_south <span class="op">=</span> df[(df[<span class="st">'Year'</span>] <span class="op">==</span> <span class="dv">2023</span>) <span class="op">&amp;</span> (df[<span class="st">'Region'</span>] <span class="op">==</span> <span class="st">'South'</span>)]</span>
<span id="cb27-11"><a href="#cb27-11" aria-hidden="true" tabindex="-1"></a>county_ev_totals <span class="op">=</span> data_2023_south.groupby(<span class="st">'County'</span>)[<span class="st">'Electric Vehicle (EV) Total'</span>].<span class="bu">sum</span>()</span>
<span id="cb27-12"><a href="#cb27-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-13"><a href="#cb27-13" aria-hidden="true" tabindex="-1"></a>top5_counties <span class="op">=</span> county_ev_totals.sort_values(ascending<span class="op">=</span><span class="va">False</span>).head(<span class="dv">5</span>)</span>
<span id="cb27-14"><a href="#cb27-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-15"><a href="#cb27-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-16"><a href="#cb27-16" aria-hidden="true" tabindex="-1"></a>mean_south <span class="op">=</span> top5_counties.mean()</span>
<span id="cb27-17"><a href="#cb27-17" aria-hidden="true" tabindex="-1"></a>mean_northeast <span class="op">=</span> top5_counties_northeast.mean()</span>
<span id="cb27-18"><a href="#cb27-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-19"><a href="#cb27-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform a t-test</span></span>
<span id="cb27-20"><a href="#cb27-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Since we are doing a one-tailed test, we need to divide the p-value by 2</span></span>
<span id="cb27-21"><a href="#cb27-21" aria-hidden="true" tabindex="-1"></a>t_stat, p_value <span class="op">=</span> ttest_ind(top5_counties, top5_counties_northeast, equal_var<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb27-22"><a href="#cb27-22" aria-hidden="true" tabindex="-1"></a>p_value_one_tailed <span class="op">=</span> p_value <span class="op">/</span> <span class="dv">2</span></span>
<span id="cb27-23"><a href="#cb27-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-24"><a href="#cb27-24" aria-hidden="true" tabindex="-1"></a>mean_south, mean_northeast, t_stat, p_value_one_tailed </span>
<span id="cb27-25"><a href="#cb27-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-26"><a href="#cb27-26" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"t-stat:"</span>,t_stat)</span>
<span id="cb27-27"><a href="#cb27-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"p_value"</span>,p_value_one_tailed)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>t-stat: 0.07371697182914644
p_value 0.4715510434929737</code></pre>
</div>
</div>
<p><strong>Conclusion for SMART Q3:</strong></p>
<p>The p-value is much higher than the commonly used significance level of 0.05 so we failed to reject null hypothesis so we conclude that the mean number of EVs in the top 5 counties of the South region is less than that in the top 5 counties of the Northeast region. We have seen that the trend of EV adoption in each region in that we have seen Northeast have higher adoption than south from 2022 to 2023 we are using the above test to check northeast adoption or increase of ev not due to top5 counties but rather average of all counties from the t-test the top5 south region having highest EV adoption but overall it decreased</p>
</section>
</section>
</section>
</section>
<section id="modelling" class="level1" data-number="9">
<h1 data-number="9"><span class="header-section-number">9</span> MODELLING</h1>
<section id="ols-regression" class="level2" data-number="9.1">
<h2 data-number="9.1" class="anchored" data-anchor-id="ols-regression"><span class="header-section-number">9.1</span> OLS Regression</h2>
<section id="smart-question-4-is-there-a-relationship-between-the-year-and-total-vehicle-count-in-predicting-regional-ev-adoption" class="level3" data-number="9.1.1">
<h3 data-number="9.1.1" class="anchored" data-anchor-id="smart-question-4-is-there-a-relationship-between-the-year-and-total-vehicle-count-in-predicting-regional-ev-adoption"><span class="header-section-number">9.1.1</span> SMART QUESTION 4: Is there a relationship between the year and total vehicle count in predicting regional EV adoption?</h3>
<div class="cell" data-execution_count="21">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Preparing the data for linear regression</span></span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 'Year' and 'Total Vehicles' will be our independent variables (predictors)</span></span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 'Electric Vehicle (EV) Total' is the dependent variable (target)</span></span>
<span id="cb29-8"><a href="#cb29-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-9"><a href="#cb29-9" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[<span class="st">'Year'</span>, <span class="st">'Total Vehicles'</span>]]  <span class="co"># Independent variables</span></span>
<span id="cb29-10"><a href="#cb29-10" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'Electric Vehicle (EV) Total'</span>]  <span class="co"># Dependent variable</span></span>
<span id="cb29-11"><a href="#cb29-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-12"><a href="#cb29-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding a constant to the model (intercept)</span></span>
<span id="cb29-13"><a href="#cb29-13" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> sm.add_constant(X)</span>
<span id="cb29-14"><a href="#cb29-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-15"><a href="#cb29-15" aria-hidden="true" tabindex="-1"></a><span class="co"># Building the linear regression model</span></span>
<span id="cb29-16"><a href="#cb29-16" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> sm.OLS(y, X).fit()</span>
<span id="cb29-17"><a href="#cb29-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-18"><a href="#cb29-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Getting the summary of the regression</span></span>
<span id="cb29-19"><a href="#cb29-19" aria-hidden="true" tabindex="-1"></a>model_summary <span class="op">=</span> model.summary()</span>
<span id="cb29-20"><a href="#cb29-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-21"><a href="#cb29-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the summary</span></span>
<span id="cb29-22"><a href="#cb29-22" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(model_summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:     Electric Vehicle (EV) Total   R-squared:                       0.591
Model:                                     OLS   Adj. R-squared:                  0.591
Method:                          Least Squares   F-statistic:                     9158.
Date:                         Tue, 19 Dec 2023   Prob (F-statistic):               0.00
Time:                                 17:33:45   Log-Likelihood:                -23297.
No. Observations:                        12688   AIC:                         4.660e+04
Df Residuals:                            12685   BIC:                         4.662e+04
Df Model:                                    2                                         
Covariance Type:                     nonrobust                                         
==================================================================================
                     coef    std err          t      P&gt;|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const           -495.3557     14.768    -33.543      0.000    -524.302    -466.409
Year               0.2457      0.007     33.611      0.000       0.231       0.260
Total Vehicles     0.0065   4.85e-05    134.544      0.000       0.006       0.007
==============================================================================
Omnibus:                     5488.968   Durbin-Watson:                   2.000
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           181296.233
Skew:                           1.440   Prob(JB):                         0.00
Kurtosis:                      21.293   Cond. No.                     2.22e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.22e+06. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
</div>
<p><strong>Conclusion for SMART Q4:</strong></p>
<p>With an R-squared of 0.591, the OLS regression model demonstrates a significant relationship between the year, total vehicle count, and regional EV adoption. This means that the model accounts for approximately 59% of the variation in EV adoption. The year and total vehicle count are significant predictors (p 0.0001), indicating that temporal changes and vehicle availability play a role. The high condition number, on the other hand, indicates the possibility of multicollinearity, which may affect the reliability of the regression coefficients. The model emphasises the significance of time trends and vehicle accessibility in influencing regional EV adoption.</p>
</section>
</section>
<section id="logisticregression" class="level2" data-number="9.2">
<h2 data-number="9.2" class="anchored" data-anchor-id="logisticregression"><span class="header-section-number">9.2</span> LogisticRegression</h2>
<section id="smart-q5-can-demographic-and-regional-factors-such-as-year-state-and-region-effectively-predict-the-likelihood-of-a-county-having-high-electric-vehicle-adoption-rates" class="level3" data-number="9.2.1">
<h3 data-number="9.2.1" class="anchored" data-anchor-id="smart-q5-can-demographic-and-regional-factors-such-as-year-state-and-region-effectively-predict-the-likelihood-of-a-county-having-high-electric-vehicle-adoption-rates"><span class="header-section-number">9.2.1</span> SMART Q5: Can demographic and regional factors, such as year, state, and region, effectively predict the likelihood of a county having high electric vehicle adoption rates?</h3>
<p><strong>Task:</strong></p>
<p>Predict whether a county has a high or low adoption of electric vehicles based on the provided features.</p>
<p><strong>Target Variable:</strong></p>
<p>Create a binary target variable (e.g., “High EV Adoption” vs.&nbsp;“Low EV Adoption”) based on a threshold of Percent Electric Vehicles. Logistic Regression: Use logistic regression to model the likelihood of high EV adoption based on the other features.</p>
<div class="cell" data-execution_count="22">
<details>
<summary>Show the code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">"ignore"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the threshold for high vs. low EV adoption (you can adjust this threshold)</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>threshold <span class="op">=</span> <span class="fl">5.0</span>  <span class="co"># For example, counties with &gt;5% adoption are considered "high" adoption</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a binary target variable based on the threshold</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'HighEVAdoption'</span>] <span class="op">=</span> (df[<span class="st">'Percent Electric Vehicles'</span>] <span class="op">&gt;</span> threshold).astype(<span class="bu">int</span>)</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the predictors (features)</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> df[[<span class="st">'Year'</span>, <span class="st">'Electric Vehicle (EV) Total'</span>, <span class="st">'State'</span>, <span class="st">'Region'</span>]]</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the target variable</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> df[<span class="st">'HighEVAdoption'</span>]</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Perform one-hot encoding for the categorical columns</span></span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a>X <span class="op">=</span> pd.get_dummies(X, columns<span class="op">=</span>[<span class="st">'State'</span>, <span class="st">'Region'</span>], drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Split the dataset into training and testing sets</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a>X_train, X_test, y_train, y_test <span class="op">=</span> train_test_split(X, y, test_size<span class="op">=</span><span class="fl">0.2</span>, random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the features</span></span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()</span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a>X_train_scaled <span class="op">=</span> scaler.fit_transform(X_train)</span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a>X_test_scaled <span class="op">=</span> scaler.transform(X_test)</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Create and train the logistic regression model</span></span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LogisticRegression(random_state<span class="op">=</span><span class="dv">42</span>)</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a>model.fit(X_train_scaled, y_train)</span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a>y_pred <span class="op">=</span> model.predict(X_test_scaled)</span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-41"><a href="#cb31-41" aria-hidden="true" tabindex="-1"></a><span class="co"># Evaluate the model (you can print accuracy, precision, recall, etc., as needed)</span></span>
<span id="cb31-42"><a href="#cb31-42" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score, classification_report</span>
<span id="cb31-43"><a href="#cb31-43" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Accuracy:"</span>, accuracy_score(y_test, y_pred))</span>
<span id="cb31-44"><a href="#cb31-44" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Classification Report:"</span>)</span>
<span id="cb31-45"><a href="#cb31-45" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(classification_report(y_test, y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Accuracy: 0.8175728920409772
Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      1960
           1       0.70      0.34      0.46       578

    accuracy                           0.82      2538
   macro avg       0.77      0.65      0.68      2538
weighted avg       0.80      0.82      0.79      2538
</code></pre>
</div>
</div>
<p><strong>Conclusion for SMART Q5:</strong></p>
<p>With an accuracy of 81.76%, the logistic regression model suggests that demographic and regional factors can be moderately effective in predicting high electric vehicle adoption rates at the county level. Precision in predicting high adoption counties is significantly lower than in predicting low adoption counties, indicating some difficulties in identifying counties with high EV adoption solely based on these factors. The model predicts low adoption rates with high precision and recall, which may reflect a more consistent set of negative indicators across counties. Overall, while the model is useful, it could benefit from the addition of more variables to improve its predictive power for high adoption rates.</p>
</section>
</section>
</section>
<section id="future-scope" class="level1" data-number="10">
<h1 data-number="10"><span class="header-section-number">10</span> FUTURE SCOPE</h1>
<p>Certainly! Building on your suggestions for future scope involving the implementation of decision tree analysis and state-wise modeling, here’s some additional ideas:</p>
<p>In contemplating the future scope of our project with the Electric Vehicle (EV) population dataset, several promising directions present themselves. Firstly, we can enhance our classification analysis by employing decision tree models, which may offer increased accuracy and better interpretability. Decision trees can effectively handle complex datasets and provide clear insights into how different variables interact to influence EV adoption. Additionally, undertaking a state-wise analysis and modeling could yield more granular insights, revealing unique trends and adoption patterns that vary across states. This approach would allow for tailored strategies that address specific regional characteristics.</p>
<p>Finally, exploring machine learning techniques like neural networks or ensemble methods could further refine our predictive models. These advanced techniques are adept at capturing non-linear relationships and interactions between variables, which could unveil more nuanced insights into EV adoption patterns.</p>
</section>
<section id="conclusion" class="level1" data-number="11">
<h1 data-number="11"><span class="header-section-number">11</span> CONCLUSION</h1>
<p>The analysis demonstrates a prominent trend in the adoption of Electric Vehicles (EVs), with the Western region emerging as the leader, closely trailed by the Northeast. This trend is largely influenced by the unique characteristics of these areas. Both regions are recognized for their robust environmental advocacy and forward-thinking energy policies that promote the use of clean and sustainable energy sources, including EVs. These policies typically encompass various incentives such as tax deductions, financial grants, and support for EV infrastructure development.</p>
<p>Additionally, the Western and Northeastern regions are characterized by a denser presence of urban centers. In such settings, the uptake of novel technologies, including EVs, is generally quicker. This can be attributed to factors like higher average income, a stronger sense of environmental responsibility, and the availability of superior EV charging facilities.</p>
<p>Furthermore, these regions often face higher fuel prices compared to other parts of the country, making the option of EVs more financially appealing. The presence of significant technological centers like Silicon Valley in the Western region, along with renowned educational and research institutions in the Northeast, creates an environment more conducive to adopting new technologies such as EVs. Collectively, these elements play a crucial role in the heightened rates of EV adoption seen in the Western and Northeastern United States, mirroring a synergy of policy, economic, and cultural factors.</p>
<p>The logistic regression analysis provided insights into predicting whether a county has a high or low rate of EV adoption. The model demonstrated a reliable performance with an accuracy of 81% and a precision rate of 0.83, signifying its dependability in making these predictions.</p>
</section>
<section id="references" class="level1" data-number="12">
<h1 data-number="12"><span class="header-section-number">12</span> REFERENCES</h1>
<ol type="1">
<li><p>Singh, V., Singh, V., &amp; Vaibhav, S. (2020). A review and simple meta-analysis of factors influencing adoption of electric vehicles. Transportation Research Part D: Transport and Environment, 86, 102436.</p></li>
<li><p>Debnath, R., Bardhan, R., Reiner, D. M., &amp; Miller, J. R. (2021). Political, economic, social, technological, legal and environmental dimensions of electric vehicle adoption in the United States: A social-media interaction analysis. Renewable and Sustainable Energy Reviews, 152, 111707.</p></li>
<li><p>Broadbent, G. H., Drozdzewski, D., &amp; Metternicht, G. (2018). Electric vehicle adoption: An analysis of best practice and pitfalls for policy making from experiences of Europe and the US. Geography compass, 12(2), e12358.</p></li>
</ol>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



<script src="SummaryPaper_FinalProject_T1_files/libs/quarto-html/zenscroll-min.js"></script>
</body></html>